name: cellviewer
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - napari
  - numpy
  - pandas
  - pandas-profiling
  - path.py
  - pip
  - pyqt
  - python=3.9.1
  - qt>=5.12.3
  - read-roi
  - scikit-learn
  - seaborn
  - shapely
  - statsmodels
  - pip:
      - nbdime
      - pyhere
      - pylint